sonar.projectKey=_the-orbit-fe
sonar.organization=L02-bang6chia3
sonar.projectName=The Orbit FE
sonar.projectVersion=1.0.0

sonar.sources=the-orbit-fe/app
sonar.tests=the-orbit-fe/__tests__
sonar.test.inclusions=**/*.test.tsx

sonar.exclusions=the-orbit-be/**, **/node_modules/**, **/assets/**, **/*.d.ts

sonar.javascript.lcov.reportPaths=the-orbit-fe/coverage/lcov.info
sonar.sourceEncoding=UTF-8